name: test and front deplo

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [fst-chat, fst-chat-back]

    steps:
        # Désactiver Husky en CI
      - name: Disable Husky
        run: echo "HUSKY=0" >> $GITHUB_ENV
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      # 3. Installer les dépendances du projet correspondant
      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: npm install

      # 4. Exécuter les tests
      - name: Run tests
        working-directory: ${{ matrix.project }}
        run: npm test
  pushToprod:
      runs-on: ubuntu-latest
      needs: test
      if: github.ref == 'refs/heads/master'
      steps:
       - name: Checkout repository
         uses: actions/checkout@v5
       - name: pushToAnotherRepo
         uses: cpina/github-action-push-to-another-repository@v1.7.2
         env: 
           API_TOKEN_GITHUB: ${{secrets.AUTH_TOKEN}}
         with:
          source-directory: fst-chat/
          destination-github-username: nokzs
          destination-repository-name: fstChatTestFrontDeploy
          user-email: alexischapusot@gmail.com
          target-branch: master
          ignore: github/**
